# Generated by Django 5.1.3 on 2024-11-11 17:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0002_transaction_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="date",
        ),
        migrations.AddField(
            model_name="transaction",
            name="date_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
